[package]
name = "rofi-steam-game-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyvalues-parser = "0.1"
fork = "0.1"
