[package]
name = "home-daemon"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3", features = ["tokio"] }
futures-util = "0.3"
swayipc-async = "2"
cpal = "0.15"
serde = { version = "1.0.219", features = ["derive"] }
dashmap = "6.1.0"
mailparse = "0.16.1"

[dependencies.tokio]
version = "1"
features = ["rt", "macros", "process"]
