# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  atf-bpir3 = {
    pname = "atf-bpir3";
    version = "c30a1caf8274af67bf31f3fb5abc45df5737df36";
    src = fetchTarball {
      url = "https://github.com/frank-w/u-boot/archive/c30a1caf8274af67bf31f3fb5abc45df5737df36.tar.gz";
      sha256 = "sha256-pW2yytXRIFEIbG1gnuXq8TiLe/Eew7zESe6Pijh2qVk=";
    };
    date = "2022-12-13";
  };
  fastforward = {
    pname = "fastforward";
    version = "0.2237";
    src = fetchurl {
      url = "https://github.com/FastForwardTeam/FastForward/releases/download/0.2237/fastforwardteam-0.2237.xpi";
      sha256 = "sha256-mrWvbjqUphMKi8ItRFSmRAzMyzsqB9rJbZFm+I7ocSc=";
    };
  };
  proton-ge = {
    pname = "proton-ge";
    version = "GE-Proton8-6";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-6/GE-Proton8-6.tar.gz";
      sha256 = "sha256-0ePO6ZzsZpAb9iM++k4fYDwKzJpuZNgfPKwZePAUc0Y=";
    };
  };
  searxng = {
    pname = "searxng";
    version = "cada89ee3648de6ca5b458aeacafe6c10d5230a2";
    src = fetchTarball {
      url = "https://github.com/searxng/searxng/archive/cada89ee3648de6ca5b458aeacafe6c10d5230a2.tar.gz";
      sha256 = "sha256-eOq4vZ8690H1lCRu8LXgUJvc/4lY+VqvVOqRyEURreI=";
    };
    date = "2023-07-07";
  };
}
