# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  atf-bpir3 = {
    pname = "atf-bpir3";
    version = "c30a1caf8274af67bf31f3fb5abc45df5737df36";
    src = fetchTarball {
      url = "https://github.com/frank-w/u-boot/archive/c30a1caf8274af67bf31f3fb5abc45df5737df36.tar.gz";
      sha256 = "sha256-pW2yytXRIFEIbG1gnuXq8TiLe/Eew7zESe6Pijh2qVk=";
    };
    date = "2022-12-13";
  };
  proton-ge = {
    pname = "proton-ge";
    version = "GE-Proton9-11";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton9-11/GE-Proton9-11.tar.gz";
      sha256 = "sha256-vpr4DVWI7TZWb+roijpX5kJRPOJT4wZhT/ZnRrkgZKI=";
    };
  };
  searxng = {
    pname = "searxng";
    version = "f1c05e7c16e59a8d5d98640bc057958ea268cddf";
    src = fetchTarball {
      url = "https://github.com/searxng/searxng/archive/f1c05e7c16e59a8d5d98640bc057958ea268cddf.tar.gz";
      sha256 = "sha256-2QetT4xLlyKAC/eiIhShYRMRwFU9dJm6Ah5wS84Rgf8=";
    };
    date = "2024-08-09";
  };
}
